
server:
  port: 5050
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      #      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
      defaultZone: http://localhost:${server.port}/eureka/


spring:
  application:
    name: monitor-server